# Interactive component

<div id="chart" style="width: 700px; float:left;"></div>
<div id="text" style="width: 400px; float: left;"></div>

<script src="https://d3js.org/d3.v6.js"></script>
<script>

      var chart = d3.select("div#chart")
      chart.style("width: 700px; float:left;")
      chart.append("h3").text("Proportion of Vitamins among different countries")
      chart.append("p").text("In this graph you can choose to see the proportion of different vitamins among different countries by simply selecting the countries at the bottom. Also you can see the details of the proportion down there, the number will change as you select different countries.")
      var text = d3.select("div#text")
      text.style("width: 400px; float: left;")
      text.append("h3").text("Countries: ")
            .append("span").attr("id","countries_en")
      text.append("p").text("Vitamin A: ")
            .append("span").attr("id","vitamin_a")
      text.append("p").text("Vitamin B1: ")
            .append("span").attr("id","vitamin_b1")
      text.append("p").text("Vitamin B2: ")
            .append("span").attr("id","vitamin_b2")
      text.append("p").text("Vitamin C: ")
            .append("span").attr("id","vitamin_c")
      text.append("p").text("Vitamin D: ")
            .append("span").attr("id","vitamin_d")
      text.append("p").text("Vitamin E: ")
            .append("span").attr("id","vitamin_e")
      function update_text(data,countries_en){
        d3.select("#countries_en").text(countries_en)
        var vitamin_a = (Number(data[0])*100).toFixed(2)
        var vitamin_b1 = (Number(data[1])*100).toFixed(2)
        var vitamin_b2 = (Number(data[2])*100).toFixed(2)
        var vitamin_c = (Number(data[3])*100).toFixed(2)
        var vitamin_d = (Number(data[4])*100).toFixed(2)
        var vitamin_e = (Number(data[5])*100).toFixed(2)
        d3.select("#vitamin_a").text(vitamin_a+"%")
        d3.select("#vitamin_b1").text(vitamin_b1+"%")
        d3.select("#vitamin_b2").text(vitamin_b2+"%")
        d3.select("#vitamin_c").text(vitamin_c+"%")
        d3.select("#vitamin_d").text(vitamin_d+"%")
        d3.select("#vitamin_e").text(vitamin_e+"%")
      }
      function update(data,country) {
        update_text(data,country)
        var bars = svg.selectAll("rect")   // data join
                      .data(data);
        xScale = d3.scaleBand()
                    .domain(d3.range(data.length))
                    .range([0, innerWidth])
                    .paddingInner(.2);

        yScale = d3.scaleLinear()
                    .domain([0, 1])
                    .range([innerHeight, 0])
        
        bars.enter()
            .append("rect")    // add new elements
            .attr("x", (d, i) => xScale(i))
            .attr("y", (d, i)=> yScale(d))
            .attr("width", xScale.bandwidth())
            .attr("height", d => innerHeight - yScale(d))
            .attr("fill", "lightgreen")
          .merge(bars)    // merge
            .transition()
            .duration(2000)
            .attr("x", (d, i) => xScale(i))
            .attr("y", (d, i)=> yScale(d))
            .attr("width", xScale.bandwidth())
            .attr("height", d => innerHeight - yScale(d))
            .attr("fill", "lightgreen");

    bars.exit().remove();    // remove extra elements
    }
      var w = 600;
      var h = 500;
      var margin = {top: 30, right: 30, bottom: 30, left: 30};
      var innerWidth = w - margin.left - margin.right;
      var innerHeight = h - margin.top - margin.bottom;

      var svg = d3.select("div#chart")
        .append("svg")
          .attr("width", w)
          .attr("height", h);

      d3.csv("https://raw.githubusercontent.com/Maochenhui123/Data/main/d3/vitamins_countries.csv")
        .then(
              function(data){
                console.log(data)
                var countries = {};
                var bardata = [];
                let len = data.length
                let init_country = data[0].countries_en
                for(var i=0; i<data.length;i++){
                  let countries_en = data[i].countries_en
                  if(data[i].countries_en in countries){
                    countries[countries_en].push(Number(data[i].proportion).toFixed(5))
                  }else{
                    countries[countries_en] = [Number(data[i].proportion).toFixed(5)]
                  }
                }
                
                bardata = countries[init_country]
                update_text(bardata,init_country)
                var xScale = d3.scaleBand()
                              .domain(d3.range(bardata.length))
                              .range([0, innerWidth])
                              .paddingInner(.2);

                var vitamins = d3.scaleBand()
                                  .range([0, innerWidth])
                                  .domain(["vitamins.a","vitamins.b1","vitamins.b2","vitamins.c","vitamins.d","vitamins.e"])
                var yScale = d3.scaleLinear()
                                .domain([0, 1])
                                .range([innerHeight, 0])

                var xAxis = d3.axisBottom()
                      .scale(vitamins);
                      
                var yAxis = d3.axisLeft()
                      .scale(yScale);
                svg.append("g")
                    .attr("class", "xAxis")
                    .attr("transform", `translate (${margin.left}, ${h - margin.bottom})`)
                    .call(xAxis);

                svg.append("g")
                    .attr("class", "yAxis")
                    .attr("transform", `translate (${margin.left}, ${margin.top})`)
                    .call(yAxis);
                var bars = svg.append("g")
                              .attr("id", "plot")
                              .attr("transform", `translate (${margin.left}, ${margin.top})`)
                              .selectAll("rect")
                              .data(bardata);

                bars.enter().append("rect")
                    .attr("x", (d, i) => xScale(i))
                    .attr("y", (d, i)=> yScale(d))
                    .attr("width", xScale.bandwidth())
                    .attr("height", d => innerHeight - yScale(d))
                    .attr("fill", "lightgreen")
                    .append("title")
                    .text(function(d){
                      return d;
                    });
                    var countries_en = Object.keys(countries)
                    var selector = d3.select("div#chart")
                       .append("div").attr("id","interactive")
                       .append("select").attr("id","bar")
                       .on("change",function(d){
                          var selection = document.getElementById("bar");
                          var country = selection.value;
                          var data = countries[country]
                          update(data,country)
                          d3.selectAll("rect")
                            .select("title")
                            .text(function(d){
                          return d;
                        });
                      })
      
                    selector.selectAll("option")
                       .data(countries_en)
                       .enter().append("option")
                       .attr("value", d=>d)
                       .text(d=>d)
                    }
                  );

      
</script>

