--- 
title: "Hidden Fact of Food Market"
author: "Chenhui Mao, Yena Lee, Ellen Chen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In this project we are interested in figuring out trends and patterns of nutrition information of food products in supermarkets over the world. We chose to use the Open Food Facts database to obtain nutrition information, countries, supermarkets, brands, serving size, categories etc. Three main questions we would like to answers are

- How are the levels of energy and vitamins containing food products in markets different among different countries? We want to know if there exist patterns in the levels of energy and each vitamin in different countries.
- Which country eats the most sugar? We compare sugar levels of products in different countries and see if the countries with products of generally high sugar level also appear on Diabetes prevalence country ranking.
- What are the most frequent keywords in a Keto-friendly product in the US and France supermarkets? With Keto Certified standards, we label Keto-friendly products in markets and create keyword maps called WordClouds to compare the most frequent keywords used in ordinary products and Keto-friendly products in a specific country.
